# Generated by Django 4.0.6 on 2022-11-12 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_myuser_user_type'),
        ('rezerwacje', '0004_rename_appointment_rezerwacje_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rezerwacje',
            old_name='date',
            new_name='data',
        ),
        migrations.RenameField(
            model_name='rezerwacje',
            old_name='timeslot',
            new_name='godzina',
        ),
        migrations.AlterUniqueTogether(
            name='rezerwacje',
            unique_together={('lekarz', 'data', 'godzina')},
        ),
    ]
