# Generated by Django 4.0.6 on 2022-11-12 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rezerwacje', '0005_rename_date_rezerwacje_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rezerwacje',
            name='data',
            field=models.DateField(),
        ),
    ]
