# Generated by Django 4.0.6 on 2022-11-15 17:31

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('rezerwacje', '0006_alter_rezerwacje_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kontakt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imieinazwisko', models.CharField(max_length=50, verbose_name='Imie i nazwisko')),
                ('email', models.EmailField(max_length=254, verbose_name='Adres email')),
                ('telefon', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Telefon')),
                ('tytul', models.CharField(max_length=250, verbose_name='Tytuł wiadomości')),
                ('wiadomosc', models.TextField(verbose_name='Treść wiadomości')),
            ],
            options={
                'verbose_name_plural': 'Kontakt',
            },
        ),
    ]
