# Generated by Django 4.0.6 on 2022-11-15 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rezerwacje', '0007_kontakt'),
    ]

    operations = [
        migrations.AddField(
            model_name='kontakt',
            name='submit_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
