# Generated by Django 4.0.6 on 2022-11-17 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rezerwacje', '0009_alter_rezerwacje_godzina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rezerwacje',
            name='godzina',
            field=models.IntegerField(choices=[(0, '08:00'), (1, '08:30'), (2, '09:00'), (3, '09:30'), (4, '10:00'), (5, '10:30 '), (6, '11:00 '), (7, '11:30 '), (8, '12:00 '), (9, '12:30 '), (10, '13:00 '), (11, '13:30 '), (12, '14:00 '), (13, '14:30 '), (14, '15:00 '), (15, '15:30 ')]),
        ),
    ]
