# Generated by Django 4.0.6 on 2022-11-07 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='telefon',
            field=models.CharField(blank=True, max_length=9, null=True, unique=True, verbose_name='Telefon'),
        ),
    ]
