# Generated by Django 4.0.6 on 2022-11-07 16:54

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_myuser_telefon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='telefon',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True, verbose_name='Telefon'),
        ),
    ]
