# Generated by Django 4.0.6 on 2022-11-07 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_myuser_telefon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='PESEL',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
    ]
