# Generated by Django 4.0.6 on 2022-11-07 18:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_myuser_pesel'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='data_urodzenia',
            field=models.DateField(blank=True, null=True, verbose_name='Data Urodzenia'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='gmina',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Gmina'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='kod_pocztowy',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Kod pocztowy'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='miejscowosc',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Miejscowość'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='numer_domu',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Numer domu'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='plec',
            field=models.CharField(blank=True, choices=[('0', 'Mężczyzna'), ('1', 'Kobieta')], max_length=20, null=True, verbose_name='Płeć'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='powiat',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Powiat'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='ulica',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Ulica'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='wojewodztwo',
            field=models.CharField(blank=True, choices=[('lower_silesia', 'Lower Silesian'), ('kuyavia-pomerania', 'Kuyavian-Pomeranian'), ('lublin', 'Lublin'), ('lubusz', 'Lubusz'), ('lodz', 'Lodz'), ('lesser_poland', 'Lesser Poland'), ('masovia', 'Masovian'), ('opole', 'Opole'), ('subcarpatia', 'Subcarpathian'), ('podlasie', 'Podlasie'), ('pomerania', 'Pomeranian'), ('silesia', 'Silesian'), ('swietokrzyskie', 'Swietokrzyskie'), ('warmia-masuria', 'Warmian-Masurian'), ('greater_poland', 'Greater Poland'), ('west_pomerania', 'West Pomeranian')], max_length=30, null=True, verbose_name='Województwo'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='PESEL',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(11)]),
        ),
    ]
