# Generated by Django 4.0.6 on 2022-11-08 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_myuser_data_urodzenia_myuser_gmina_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='konto_pics'),
        ),
    ]
