# Generated by Django 4.0.6 on 2022-11-10 17:27

from django.conf import settings
import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_myuser_data_urodzenia_remove_myuser_gmina_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='PESEL',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='image',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='kod_pocztowy',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='miejscowosc',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='numer_domu',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='numer_lokalu',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='ulica',
        ),
        migrations.CreateModel(
            name='Lekarze',
            fields=[
                ('myuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('image', models.ImageField(default='default.jpg', upload_to='lekarz_pics')),
                ('specjalizacja', models.CharField(choices=[('1', 'Lekarz rodzinny'), ('2', 'Ortopedia'), ('3', 'Stomatologia'), ('4', 'Kardiologia'), ('5', 'Ginekologia'), ('6', 'Neurologia'), ('7', 'Dermatologia'), ('8', 'Okulistyka'), ('9', 'Urologia')], max_length=50, verbose_name='Specjalność')),
            ],
            options={
                'ordering': ['specjalizacja', 'nazwisko'],
            },
            bases=('users.myuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Pacjenci',
            fields=[
                ('myuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('image', models.ImageField(default='default.jpg', upload_to='konto_pics')),
                ('PESEL', models.CharField(blank=True, max_length=11, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(11)])),
                ('kod_pocztowy', models.CharField(blank=True, max_length=30, null=True, verbose_name='Kod pocztowy')),
                ('miejscowosc', models.CharField(blank=True, max_length=30, null=True, verbose_name='Miejscowość')),
                ('ulica', models.CharField(blank=True, max_length=30, null=True, verbose_name='Ulica')),
                ('numer_domu', models.CharField(blank=True, max_length=10, null=True, verbose_name='Numer domu')),
                ('numer_lokalu', models.CharField(blank=True, max_length=10, null=True, verbose_name='Numer lokalu')),
            ],
            options={
                'ordering': ['imie', 'nazwisko'],
            },
            bases=('users.myuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
