# Generated by Django 4.0.6 on 2022-11-10 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_myuser_pesel_remove_myuser_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='user_type',
            field=models.CharField(choices=[('L', 'Lekarz'), ('P', 'Pacjent')], default='P', max_length=1, verbose_name='Typ'),
        ),
    ]
