# Generated by Django 4.0.6 on 2022-11-10 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_myuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lekarze',
            name='image',
            field=models.ImageField(default='docdef.png', upload_to='lekarz_pics'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='user_type',
            field=models.CharField(choices=[('M', 'Moderator'), ('L', 'Lekarz'), ('P', 'Pacjent')], max_length=1, verbose_name='Typ'),
        ),
    ]
