# Generated by Django 4.0.6 on 2022-11-10 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_lekarze_image_alter_myuser_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='lekarze',
            name='tytul',
            field=models.CharField(blank=True, choices=[('1', 'lek.'), ('2', 'lek. dent.'), ('3', 'dr n. med.'), ('4', 'dr hab n. med.'), ('5', 'prof. dr hab')], max_length=15, null=True, verbose_name='Tytuł'),
        ),
        migrations.AlterField(
            model_name='lekarze',
            name='specjalizacja',
            field=models.CharField(blank=True, choices=[('1', 'Lekarz rodzinny'), ('2', 'Ortopedia'), ('3', 'Stomatologia'), ('4', 'Kardiologia'), ('5', 'Ginekologia'), ('6', 'Neurologia'), ('7', 'Dermatologia'), ('8', 'Okulistyka'), ('9', 'Urologia')], max_length=50, null=True, verbose_name='Specjalność'),
        ),
    ]
