# Generated by Django 4.0.6 on 2022-11-10 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_lekarze_image_remove_pacjenci_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='image',
        ),
        migrations.AddField(
            model_name='lekarze',
            name='image',
            field=models.ImageField(default='docdef.jpg', upload_to='konto_pics'),
        ),
        migrations.AddField(
            model_name='pacjenci',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='konto_pics'),
        ),
    ]
