# Generated by Django 4.0.6 on 2022-11-10 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_remove_myuser_image_lekarze_image_pacjenci_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lekarze',
            name='image',
            field=models.ImageField(default='docdef.png', upload_to='konto_pics'),
        ),
    ]
