# Generated by Django 4.0.6 on 2022-11-11 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_lekarze_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lekarze',
            options={'ordering': ['specjalizacja', 'nazwisko'], 'verbose_name_plural': 'Lekarze'},
        ),
        migrations.AlterModelOptions(
            name='pacjenci',
            options={'ordering': ['imie', 'nazwisko'], 'verbose_name_plural': 'Pacjenci'},
        ),
    ]
