# Generated by Django 4.0.6 on 2022-11-12 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_lekarze_options_alter_pacjenci_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='user_type',
            field=models.CharField(choices=[('M', 'Moderator'), ('L', 'Lekarz'), ('P', 'Pacjent')], default='P', max_length=1, verbose_name='Typ'),
        ),
    ]
