# Generated by Django 4.0.6 on 2022-11-12 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_alter_lekarze_tytul'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lekarze',
            name='specjalizacja',
            field=models.CharField(blank=True, choices=[('1', 'Lekarz rodzinny'), ('2', 'Ortopedia'), ('3', 'Stomatologia'), ('4', 'Kardiologia'), ('5', 'Ginekologia'), ('6', 'Neurologia'), ('7', 'Dermatologia'), ('8', 'Okulistyka'), ('9', 'Urologia')], max_length=50, null=True, verbose_name='Specjalizacja'),
        ),
    ]
